# values.yaml
replicaCount: 2

image:
  repository: amina88/backend-image
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  host: ruby-app.example.com
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 1000m
    memory: 250Mi

nodeSelector: {}
tolerations: []
affinity: {}
