# ruby-rails-chart/values.yaml

postgres:
  image: postgres:12
  db: myapp_development
  user: postgres
  password: password
  volume_size: 1Gi

rails:
  image: amina88/backend-image:latest  # The image for your Rails app
  environment:
    DATABASE_URL: postgres://postgres:password@db:5432/myapp_development
    RAILS_ENV: development
  volume_size: 1Gi
  command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
  ports:
    - "3000:3000"
