# Define the image settings
image:
  rails:
    repository: amina88/backend-image  # Your Rails app image
    tag: latest
  postgres:
    repository: postgres
    tag: "12"

# Database settings for Rails
database:
  url: postgres://postgres:password@db:5432/myapp_development
  env: development

# Rails configuration
rails:
  environment: development
  command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"

# Postgres container settings
postgres:
  image: postgres:12
  environment:
    POSTGRES_DB: myapp_development
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password

# Persistent volume claim settings
persistence:
  postgres:
    enabled: true
    size: 1Gi
  app:
    enabled: true
    size: 1Gi
