apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby-on-rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruby-on-rails-app
  template:
    metadata:
      labels:
        app: ruby-on-rails-app
    spec:
      containers:
        - name: rails-app
          image: "{{ .Values.image.rails.repository }}:{{ .Values.image.rails.tag }}"
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: {{ .Values.database.url }}
            - name: RAILS_ENV
              value: {{ .Values.rails.environment }}
          volumeMounts:
            - name: app-volume
              mountPath: /rails
          command: ["/bin/bash", "-c", "{{ .Values.rails.command }}"]
        - name: postgres
          image: "{{ .Values.postgres.image }}"
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.environment.POSTGRES_DB }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.environment.POSTGRES_USER }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.environment.POSTGRES_PASSWORD }}"
          ports:
            - containerPort: 5432

          ports:
            - containerPort: 5432
      volumes:
        - name: app-volume
          persistentVolumeClaim:
            claimName: app-pvc
