apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ruby-app-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ruby-app.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apphelm
            port:
              number: 80
  tls:
  - hosts:
    - ruby-app.example.com
    secretName: ruby-app-tls
