apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-disk  
  volumeMode: Filesystem
  volumeAttributes:
    zone: kvm.az1
    diskType: Ultra-high I/O
    encryption: Unencrypted
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-disk 
  volumeMode: Filesystem
  volumeAttributes:
    zone: kvm.az1
    diskType: Ultra-high I/O
    encryption: Unencrypted
