apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: default
  annotations:
    everest.io/disk-volume-type: SSD  
  labels:
    failure-domain.beta.kubernetes.io/region: tn-global-1
    failure-domain.beta.kubernetes.io/zone: kvm.az1
spec:
  accessModes:
  - ReadWriteOnce               # The value must be ReadWriteOnce for EVS.
  resources:
    requests:
      storage: 10Gi             # EVS disk capacity, ranging from 1 to 32768.
  storageClassName: csi-disk
  volumeMode: Filesystem
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: default
  annotations:
    everest.io/disk-volume-type: SSD 
  labels:
    failure-domain.beta.kubernetes.io/region: tn-global-1
    failure-domain.beta.kubernetes.io/zone: kvm.az1
spec:
  accessModes:
  - ReadWriteOnce               # The value must be ReadWriteOnce for EVS.
  resources:
    requests:
      storage: 10Gi             # EVS disk capacity, ranging from 1 to 32768.
  storageClassName: csi-disk
  volumeMode: Filesystem
