apiVersion: v1
kind: Service
metadata:
  name: ruby-on-rails-app
spec:
  selector:
    app: ruby-on-rails-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: ruby-on-rails-app
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
