apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby-on-rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruby-on-rails-app
  template:
    metadata:
      labels:
        app: ruby-on-rails-app
    spec:
      initContainers:
        - name: copy-app-files
          image: "{{ .Values.image.rails.repository }}:{{ .Values.image.rails.tag }}"
          command: ["/bin/bash", "-c", "cp -r /rails/* /rails"]
          volumeMounts:
            - name: app-volume
              mountPath: /rails
      containers:
        - name: rails-app
          image: "{{ .Values.image.rails.repository }}:{{ .Values.image.rails.tag }}"
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "{{ .Values.database.url }}"
            - name: RAILS_ENV
              value: "{{ .Values.rails.environment }}"
          volumeMounts:
            - name: app-volume
              mountPath: /rails
          command: ["/bin/bash", "-c", "rm -f /rails/tmp/pids/server.pid && exec rails server -b 0.0.0.0"]
      volumes:
        - name: app-volume
          persistentVolumeClaim:
            claimName: app-pvc
