apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ruby-on-rails-app  # This should match the label in the Pod template
  template:
    metadata:
      labels:
        app: ruby-on-rails-app  # This label should match the selector
    spec:
      containers:
        - name: postgres
          image: postgres:12
          env:
            - name: POSTGRES_DB
              value: "myapp_development"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "password"
          volumeMounts:
            - name: postgres-data
              mountPath: /mnt/postgresql_data  # Use a different directory outside the mount point
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
