apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
        - name: init-data-directory
          image: busybox  # Using busybox for a simple image
          command:
            - "/bin/sh"
            - "-c"
            - |
              # Ensure the directory is clean and create a subdirectory
              if [ -d "/var/lib/postgresql/data" ]; then
                rm -rf /var/lib/postgresql/data/*
              fi
              mkdir -p /var/lib/postgresql/data/db
              chown -R postgres:postgres /var/lib/postgresql/data/db
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      containers:
        - name: postgres
          image: postgres:12
          env:
            - name: POSTGRES_DB
              value: "myapp_development"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "password"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
