apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: "{{ .Values.image.react.repository }}:{{ .Values.image.react.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: CHOKIDAR_USEPOLLING
              value: "true"
          volumeMounts:
            - name: react-volume
              mountPath: /app
      volumes:
        - name: react-volume
          persistentVolumeClaim:
            claimName: react-pvc
